<?php
/**
 * Created by PhpStorm.
 * User: masgeek
 * Date: 22-Jan-18
 * Time: 11:33
 */

namespace app\api\modules\v1\models;


use app\models\DeliveryTime;

class DELIVERY_TIME_MODEL extends DeliveryTime
{

    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub

        return $fields;
    }
}