<?php

namespace common\models;

use Yii;
use \common\models\base\City as BaseCity;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "city".
 */
class City extends BaseCity
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'CITY_ID' => Yii::t('app', 'City  ID'),
            'CITY_NAME' => Yii::t('app', 'City  Name'),
            'COUNTRY_ID' => Yii::t('app', 'Country  ID'),
        ];
    }

    public static function GetCity()
    {
        $country = self::find()
            ->all();

        $listData = ArrayHelper::map($country, 'CITY_ID', 'CITY_NAME');

        return $listData;
    }
}
