<?php

namespace common\models;

use common\models\base\Status as BaseStatus;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tb_status".
 */
class Status extends BaseStatus
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'STATUS_NAME' => Yii::t('app', 'Status  Name'),
            'STATUS_DESC' => Yii::t('app', 'Status  Desc'),
            'COLOR' => Yii::t('app', 'Color'),
            'SCOPE' => Yii::t('app', 'Scope'),
            'RANK' => Yii::t('app', 'Rank'),
            'WORKFLOW' => Yii::t('app', 'Workflow'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return $this->attributeLabels();
    }

    public static function GetStatus($order_id, array $scope = ['ALL'], $workflow = 0)
    {

        $exclusion_list = self::StatusExclusionList($order_id);

        $status = self::find()
            ->where(['SCOPE' => $scope])
            ->andWhere(['WORKFLOW' => $workflow])
            ->andWhere(['NOT IN', 'STATUS_NAME', $exclusion_list])
            ->orderBy(['RANK' => SORT_ASC])
            ->all();

        $listData = ArrayHelper::map($status, 'STATUS_NAME', 'STATUS_DESC');

        return $listData;
    }

    /**
     * @param $order_id
     * @return array
     */
    public static function StatusExclusionList($order_id)
    {
        $exclusion_list = [];
        $tracked_status = OrderTracking::find()
            ->select(['STATUS'])
            ->where(['ORDER_ID' => $order_id])
            ->asArray()
            ->all();

        foreach ($tracked_status as $key => $value) {
            $exclusion_list[] = $value['STATUS'];
        }

        return $exclusion_list;
    }
}
