<?php

namespace common\models;

use common\models\base\Vehicles as BaseVehicles;

/**
 * This is the model class for table "tb_vehicles".
 */
class Vehicles extends BaseVehicles
{
    public function behaviors()
    {
        $behaviors = parent::behaviors();

        $behaviors['slug']['attribute'] = 'reg_no';

        return $behaviors;
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

}
