<?php
/**
 * Created by PhpStorm.
 * User: RONIN
 * Date: 7/16/2017
 * Time: 8:47 PM
 */

namespace api\modules\v1\controllers;

use app\api\modules\v1\models\TRACKING_MODEL;
use yii\rest\ActiveController;
use yii\web\ForbiddenHttpException;

class TimelineController extends ActiveController
{
    /**
     * @var object
     */
    public $modelClass = 'app\api\modules\v1\models\TRACKING_MODEL';

    public function actions()
    {
        $actions = parent::actions(); // TODO: Change the autogenerated stub
        return $actions;
    }

    /**
     * Checks the privilege of the current user.
     *
     * This method should be overridden to check whether the current user has the privilege
     * to run the specified action against the specified data model.
     * If the user does not have access, a [[ForbiddenHttpException]] should be thrown.
     *
     * @param string $action the ID of the action to be executed
     * @param \yii\base\Model $model the model to be accessed. If `null`, it means no specific model is being accessed.
     * @param array $params additional parameters
     * @throws ForbiddenHttpException if the user does not have access
     * @throws \yii\web\ForbiddenHttpException
     */
    public function checkAccess($action, $model = null, $params = [])
    {
        /*$api_token = Yii::$app->request->headers->get("api_token", null);
        $user_id = Yii::$app->request->headers->get("user_id", null);

        if ($api_token == null && $user_id == null) {
            throw new \yii\web\ForbiddenHttpException("You can't $action this section. $api_token");
        }
        //check if the token is valid
        if (!API_TOKEN_MODEL::IsValidToken($api_token, $user_id)) {
            throw new \yii\web\ForbiddenHttpException('Invalid token, access denied');
        }*/
    }

    /**
     * @param $order_id
     * @return TRACKING_MODEL[]|array|\yii\db\ActiveRecord[]
     * @throws ForbiddenHttpException
     */
    public function actionActiveOrders($order_id)
    {
        $this->checkAccess('active-orders');

        $orderTimeline = TRACKING_MODEL::find()
            ->where(['ORDER_ID' => $order_id])
            ->andWhere(['USER_VISIBLE' => 1])
            ->orderBy(['TRACKING_DATE' => SORT_ASC])
            ->all();

        return $orderTimeline;
    }

}