<?php

namespace backend\modules\reports\controllers;

use Yii;
use common\helper\APP_UTILS;
use common\models\VwSalesReports as ReportModel;
use common\models\search\PizzaReportSearch;
use common\controllers\BaseWebController;

class PizzaController extends BaseWebController
{
    public function behaviors()
    {
        return [];//parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new PizzaReportSearch();
        $dataProvider = $searchModel->PizzaSearch(Yii::$app->request->queryParams);

        if (Yii::$app->request->isGet) {
            $search = Yii::$app->request->get('ReportSearch');
            $orderDate = $search['ORDER_DATE'];
            $date = explode("TO", $orderDate);
            $start = isset($date[0]) ? $date[0] : APP_UTILS::FirstDayOfMonth();
            $end = isset($date[1]) ? $date[1] : APP_UTILS::LastDayOfMonth();
        }

        $startDate = APP_UTILS::FormatDate(trim($start));
        $endDate = APP_UTILS::FormatDate(trim($end));

        $this->view->title = "Pizza Types Reports between {$startDate} and {$endDate}";


        return $this->render('/report/pizza-reports', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'context' => ReportModel::CONTEXT_RIDER,
        ]);
    }


}
