<?php

namespace backend\modules\reports\controllers;

use Yii;
use common\helper\APP_UTILS;
use common\models\VwSalesReports as ReportModel;
use common\models\search\PizzaReportSearch;
use common\controllers\BaseWebController;
use common\models\search\ReportSearch;

class ReportController extends BaseWebController
{
    public function behaviors()
    {
        return [];//parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        //display a grid for selecting reports
        return 8;
    }


    public function actionGeneralReports()
    {
        $this->view->title = 'Sales & General Reports';

        $searchModel = new ReportSearch();
        $dataProvider = $searchModel->GeneralSearch(Yii::$app->request->queryParams);

        if (Yii::$app->request->isGet) {
            $search = Yii::$app->request->get('ReportSearch');
            $orderDate = $search['ORDER_DATE'];
            $date = explode("TO", $orderDate);
            $start = isset($date[0]) ? $date[0] : APP_UTILS::FirstDayOfMonth();
            $end = isset($date[1]) ? $date[1] : APP_UTILS::LastDayOfMonth();
        }

        $startDate = APP_UTILS::FormatDate(trim($start));
        $endDate = APP_UTILS::FormatDate(trim($end));


        $this->view->title = "Sales & General Reports between {$startDate} and {$endDate}";


        return $this->render('general-reports', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'context' => ReportModel::CONTEXT_GENERAL,
        ]);
    }

    public function actionSalesReports()
    {
        return $this->render('sales-reports');
    }

}
